# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

# platform :ios do
#   desc "Description of what the lane does"
#   lane :custom_lane do
#     # add actions here: https://docs.fastlane.tools/actions
#   end
# end

desc "Hello World!"
lane :hello_world do |options|
  puts "I'm here!"
end

desc "Build and run tests"
lane :build_and_run_tests do |options|
  scan(
    #clean: true,
    devices: ["iPhone 12"]
  )

  puts "Lane completed"
end
